import { z } from "zod/v4";
import { betaZodTool } from "@anthropic-ai/sdk/helpers/beta/zod";
import { queryRowsParams } from "../lib/duckdb.js";

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

const SummarizeSpendSchema = z
  .object({
    start: z.string().regex(DATE_RE, "must be YYYY-MM-DD").describe("Start of the date range, inclusive (YYYY-MM-DD)."),
    end: z.string().regex(DATE_RE, "must be YYYY-MM-DD").describe("End of the date range, exclusive (YYYY-MM-DD)."),
    group_by: z
      .enum(["category", "day", "week", "month"])
      .default("category")
      .describe("How to bucket the totals."),
    transaction_type: z
      .enum(["spend", "income", "all"])
      .default("spend")
      .describe("spend = money out (positive amount), income = money in (negative amount), all = both, netted."),
  })
  .strict();

const TRUNC_UNIT: Record<"day" | "week" | "month", string> = {
  day: "day",
  week: "week",
  month: "month",
};

/**
 * Deliberately a fixed aggregation, not left to query_warehouse's freeform
 * SQL: the arithmetic that matters most for a financial-summary answer
 * should be tested code with a known, documented sign convention, not
 * regenerated by the model on every call.
 */
export const summarizeSpendTool = betaZodTool({
  name: "summarize_spend",
  description:
    "Totals Plaid transactions over a date range, grouped by category or by time bucket. Use this for " +
    "'how much did I spend on X', 'spending by category last month', 'income vs spend in June'. " +
    "For anything this doesn't cover (specific merchants, non-Plaid sources), use query_warehouse instead.",
  inputSchema: SummarizeSpendSchema,
  run: async (args) => {
    const amountExpr = "CAST(CAST(raw_payload AS JSON)->>'$.amount' AS DOUBLE)";
    let typeFilter = "";
    let amountSelect = `SUM(${amountExpr})`;
    if (args.transaction_type === "spend") {
      typeFilter = `AND ${amountExpr} > 0`;
    } else if (args.transaction_type === "income") {
      typeFilter = `AND ${amountExpr} < 0`;
      amountSelect = `SUM(ABS(${amountExpr}))`;
    }
    // "all": no filter, amounts netted as-is (spend positive, income negative).

    let groupExpr: string;
    if (args.group_by === "category") {
      groupExpr = "COALESCE(CAST(raw_payload AS JSON)->>'$.category', 'Uncategorized')";
    } else {
      groupExpr = `CAST(date_trunc('${TRUNC_UNIT[args.group_by]}', event_timestamp) AS VARCHAR)`;
    }

    const sql = `
      SELECT
        ${groupExpr} AS group_key,
        ${amountSelect} AS total_amount,
        COUNT(*) AS transaction_count
      FROM main_analytics.fct_context_rows
      WHERE source = 'plaid'
        AND event_timestamp >= $1 AND event_timestamp < $2
        ${typeFilter}
      GROUP BY group_key
      ORDER BY total_amount DESC
    `;

    const rows = await queryRowsParams(sql, [args.start, args.end]);

    if (rows.length === 0) {
      return `No Plaid transactions found between ${args.start} and ${args.end} for transaction_type=${args.transaction_type}.`;
    }

    const grandTotal = rows.reduce((sum, r) => sum + Number(r["total_amount"]), 0);

    return JSON.stringify(
      {
        range: { start: args.start, end: args.end },
        transaction_type: args.transaction_type,
        grouped_by: args.group_by,
        grand_total: Math.round(grandTotal * 100) / 100,
        breakdown: rows.map((r) => ({
          group: r["group_key"],
          total: Math.round(Number(r["total_amount"]) * 100) / 100,
          count: Number(r["transaction_count"]),
        })),
      },
      null,
      2
    );
  },
});
